// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNQtzhMF6t08mdQKwKhC4fMDjB_KyJNVA',
    appId: '1:10042943806:web:f5dc5a170180765cb0246f',
    messagingSenderId: '10042943806',
    projectId: 'mobile-application-84412',
    authDomain: 'mobile-application-84412.firebaseapp.com',
    storageBucket: 'mobile-application-84412.appspot.com',
    measurementId: 'G-9E5KQTTQ0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUOLQ2Cw3gB24JYULL0VyGu7XmOPx2uKM',
    appId: '1:10042943806:android:d6071fe8f9a6607bb0246f',
    messagingSenderId: '10042943806',
    projectId: 'mobile-application-84412',
    storageBucket: 'mobile-application-84412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7hGE9-IgppclGVusel68KuVjx2Vh5HI',
    appId: '1:10042943806:ios:6df8b099199ce8feb0246f',
    messagingSenderId: '10042943806',
    projectId: 'mobile-application-84412',
    storageBucket: 'mobile-application-84412.appspot.com',
    iosClientId: '10042943806-ar0t63pgi00cup8611om94amoc2v20qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj7hGE9-IgppclGVusel68KuVjx2Vh5HI',
    appId: '1:10042943806:ios:6df8b099199ce8feb0246f',
    messagingSenderId: '10042943806',
    projectId: 'mobile-application-84412',
    storageBucket: 'mobile-application-84412.appspot.com',
    iosClientId: '10042943806-ar0t63pgi00cup8611om94amoc2v20qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
